- name: Atualizar servidores Linux (Ubuntu e Debian)
  hosts: linux
  become: yes
  gather_facts: yes

  tasks:
    - name: Atualizar a lista de pacotes
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Atualizar todos os pacotes instalados
      apt:
        upgrade: dist
      when: ansible_os_family == "Debian"